name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main # 當 main 分支推送時觸發部署

permissions:
  contents: write # 這一行應該放在 `jobs` 之前

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # 確保載入 Hugo 主題
          fetch-depth: 0 # 取得完整的 Git 紀錄

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages # 部署到 gh-pages 分支
